name: Verify Terraform Version in Dockerfile

on:
  pull_request:
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  extract-terraform-version:
    runs-on: ubuntu-latest
    outputs:
      terraform_version: ${{ steps.extract.outputs.terraform_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Terraform version from Dockerfile
        id: extract
        run: |
          TF_VERSION=$(grep -oP '(?<=releases\.hashicorp\.com/terraform/)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
          echo "Terraform version detected: $TF_VERSION"
          echo "terraform_version=$TF_VERSION" >> $GITHUB_OUTPUT

  verify-docker-terraform-version:
    needs: extract-terraform-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.generate-matrix.outputs.scenarios) }}

    name: Terraform ${{ needs.extract-terraform-version.outputs.terraform_version }} - ${{ matrix.scenario }}

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Terraform ${{ needs.extract-terraform-version.outputs.terraform_version }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ needs.extract-terraform-version.outputs.terraform_version }}

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "region = $AWS_REGION" >> ~/.aws/config
          export AWS_PROFILE=default

      - name: Test Terraform Version with Scenario - ${{ matrix.scenario }}
        run: |
          ROOT_DIR="$GITHUB_WORKSPACE"
          SCENARIO_DIR="$ROOT_DIR/cloudgoat/scenarios/${{ matrix.scenario }}/"

          echo "::group::Testing Scenario: ${{ matrix.scenario }} with Terraform ${{ needs.extract-terraform-version.outputs.terraform_version }}"
          echo "Testing Terraform in $SCENARIO_DIR"

          if [ ! -d "$SCENARIO_DIR" ]; then
            echo "⚠️ Skipping ${{ matrix.scenario }} (Directory not found)"
            exit 0
          fi

          cd "$SCENARIO_DIR"

          echo "1.1.1.1/32" > whitelist.txt

          if [ -f "start.sh" ]; then
            sh ./start.sh || { echo "❌ start.sh failed"; exit 1; }
          fi

          cd terraform

          terraform init || { echo "❌ Init failed"; exit 1; }
          terraform validate || { echo "❌ Validation failed"; exit 1; }
          terraform plan -out=tfplan -input=false -var='cg_whitelist=["1.1.1.1/32"]' || {
            echo "❌ Plan failed"; 
            terraform plan -no-color;
            exit 1;
          }

          echo "✔️ Terraform ${{ needs.extract-terraform-version.outputs.terraform_version }} works with ${{ matrix.scenario }}"
          echo "::endgroup::"
